version: "3.9"
services:
  nginx:
    image: openresty/openresty:alpine
    ports:
      - "80:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
    depends_on:
      - api
  api:
    build: ./container/api
